# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the action will run. 
on:
  push:
  pull_request:

jobs:

  prepare-env:
    runs-on: ubuntu-latest
    steps:
     - name: Prepare Env
        run: | 
            sudo apt install yui-compressor
            sudo apt install libxml2-utils
            wget -q https://github.com/roleoroleo/sonoff-hack/releases/download/toolchain-0.0.1/arm-sonoff-linux-uclibcgnueabi.tgz
            tar xf arm-sonoff-linux-uclibcgnueabi.tgz && rm -rf arm-sonoff-linux-uclibcgnueabi.tgz

  get-code:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - uses: actions/checkout@v2
      
      - name: Init submodules
        git submodule update --init

  build:
    runs-on: ubuntu-latest
    needs: get-code
    strategy:
            matrix:
                modules:
                - busybox
                - dropbear
                - ftpd
                - jq
                - libsqlite
                - mosquitto
                - mqtt
                - onvif_srvd
                - ptz
                - record
                - snapshot
                - static
                - wsdd
                - www

    steps:
      - name: Build Submodules
        run: |    
            bash -x ./scripts/compile_ci_pre.sh ${{ matrix.modules }}

  wrap:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy results
        run: |    
            bash -x ./scripts/compile_ci_post.sh       
            
      - name: Build stuff
        run: |    
            PATH="${PATH}:${GITHUB_WORKSPACE}/arm-sonoff-linux-uclibcgnueabi/bin/" bash -x ./scripts/pack_fw.all.sh
      
      - name: Prepare artifact
        run: |             
            cd build
            tar cf firmware.tar sonoff-hack
            gzip firmware.tar                       
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.tar.gz
          path: build/firmware.tar.gz
