# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the action will run. 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #         matrix:
    #             modules:
    #             - busybox
    #             - dropbear
    #             - ftpd
    #             - jq
    #             - libsqlite
    #             - mosquitto
    #             - mqtt
    #             - onvif_srvd
    #             - ptz
    #             - record
    #             - snapshot
    #             - static
    #             - wsdd
    #             - www

    steps:

      - uses: actions/checkout@v2
      - name: Prepare Env
        run: | 
            sudo apt install yui-compressor libxml2-utils flex 
            wget -q https://github.com/roleoroleo/sonoff-hack/releases/download/toolchain-0.0.1/arm-sonoff-linux-uclibcgnueabi.tgz
            tar xf arm-sonoff-linux-uclibcgnueabi.tgz && rm -rf arm-sonoff-linux-uclibcgnueabi.tgz
            git submodule update --init
      
      - name: Build Submodules
        run: |    
            ./scripts/compile_ci_pre.sh

      - name: Build stuff
        run: |    
            ./scripts/compile_ci_post.sh

      - name: Pack stuff
        run: |    
            sudo ./scripts/pack_fw.all.sh
            ls -la
            pwd           
            
      - name: Upload Artifact GK-200MP2B
        uses: actions/upload-artifact@v2
        with:
          path: out/GK-200MP2B/GK-200MP2B_0.1.0.tgz

      - name: Upload Artifact GK-200MP2C
        uses: actions/upload-artifact@v2
        with:
          path: out/GK-200MP2B/GK-200MP2C_*.tgz
