# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Prepare Env
        run: | 
            sudo apt install yui-compressor
            sudo apt install libxml2-utils
            wget -q https://github.com/roleoroleo/sonoff-hack/releases/download/toolchain-0.0.1/arm-sonoff-linux-uclibcgnueabi.tgz
            tar xf arm-sonoff-linux-uclibcgnueabi.tgz && rm -rf arm-sonoff-linux-uclibcgnueabi.tgz
            git submodule update --init
      
      - name: Update Builder env var
        run: | 
            echo "$(pwd)/arm-sonoff-linux-uclibcgnueabi/bin/" >> $GITHUB_PATH
      
      - name: Build stuff
        run: |    
            sudo env
            sudo ./scripts/compile.sh
            sudo ./scripts/pack_fw.all.sh
            cd build
            tar cf firmware.tar sonoff-hack
            gzip firmware.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.tar.gz
          path: build/firmware.tar.gz
